package com.github.binarywang.demo.wx.mp.dao;

import com.github.binarywang.demo.wx.mp.entity.THjcczzFormslistField;
import com.github.binarywang.demo.wx.mp.entity.THjcczzFormslistFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THjcczzFormslistFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    int countByExample(THjcczzFormslistFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    int deleteByExample(THjcczzFormslistFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    int insert(THjcczzFormslistField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    int insertSelective(THjcczzFormslistField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    List<THjcczzFormslistField> selectByExample(THjcczzFormslistFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") THjcczzFormslistField record, @Param("example") THjcczzFormslistFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    int updateByExample(@Param("record") THjcczzFormslistField record, @Param("example") THjcczzFormslistFieldExample example);
}