package com.github.binarywang.demo.wx.mp.entity;

import java.io.Serializable;

public class THjcczzTablelist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tablelist.ID
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tablelist.TABLENAME_EN
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    private String tablenameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tablelist.TABLENAME_CN
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    private String tablenameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjcczz_tablelist
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tablelist.ID
     *
     * @return the value of t_hjcczz_tablelist.ID
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tablelist.ID
     *
     * @param id the value for t_hjcczz_tablelist.ID
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tablelist.TABLENAME_EN
     *
     * @return the value of t_hjcczz_tablelist.TABLENAME_EN
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    public String getTablenameEn() {
        return tablenameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tablelist.TABLENAME_EN
     *
     * @param tablenameEn the value for t_hjcczz_tablelist.TABLENAME_EN
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    public void setTablenameEn(String tablenameEn) {
        this.tablenameEn = tablenameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tablelist.TABLENAME_CN
     *
     * @return the value of t_hjcczz_tablelist.TABLENAME_CN
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    public String getTablenameCn() {
        return tablenameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tablelist.TABLENAME_CN
     *
     * @param tablenameCn the value for t_hjcczz_tablelist.TABLENAME_CN
     *
     * @mbggenerated Fri Nov 06 10:11:29 CST 2020
     */
    public void setTablenameCn(String tablenameCn) {
        this.tablenameCn = tablenameCn;
    }
}