package com.github.binarywang.demo.wx.mp.entity;

import java.io.Serializable;

public class THjcczzFormslistField implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_formslist_field.ID
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_formslist_field.TABLENAME
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_formslist_field.ZDMC_EN
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    private String zdmcEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_formslist_field.ZDMC_ZH
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    private String zdmcZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjcczz_formslist_field
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_formslist_field.ID
     *
     * @return the value of t_hjcczz_formslist_field.ID
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_formslist_field.ID
     *
     * @param id the value for t_hjcczz_formslist_field.ID
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_formslist_field.TABLENAME
     *
     * @return the value of t_hjcczz_formslist_field.TABLENAME
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_formslist_field.TABLENAME
     *
     * @param tablename the value for t_hjcczz_formslist_field.TABLENAME
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_formslist_field.ZDMC_EN
     *
     * @return the value of t_hjcczz_formslist_field.ZDMC_EN
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public String getZdmcEn() {
        return zdmcEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_formslist_field.ZDMC_EN
     *
     * @param zdmcEn the value for t_hjcczz_formslist_field.ZDMC_EN
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public void setZdmcEn(String zdmcEn) {
        this.zdmcEn = zdmcEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_formslist_field.ZDMC_ZH
     *
     * @return the value of t_hjcczz_formslist_field.ZDMC_ZH
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public String getZdmcZh() {
        return zdmcZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_formslist_field.ZDMC_ZH
     *
     * @param zdmcZh the value for t_hjcczz_formslist_field.ZDMC_ZH
     *
     * @mbggenerated Thu Nov 19 16:28:02 CST 2020
     */
    public void setZdmcZh(String zdmcZh) {
        this.zdmcZh = zdmcZh;
    }
}