package com.github.binarywang.demo.wx.mp.entity;

import java.io.Serializable;

public class UserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.use_token
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    private String useToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_no
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    private Long userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.use_token
     *
     * @return the value of user_info.use_token
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    public String getUseToken() {
        return useToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.use_token
     *
     * @param useToken the value for user_info.use_token
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    public void setUseToken(String useToken) {
        this.useToken = useToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_no
     *
     * @return the value of user_info.user_no
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    public Long getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_no
     *
     * @param userNo the value for user_info.user_no
     *
     * @mbggenerated Fri Nov 06 10:37:59 CST 2020
     */
    public void setUserNo(Long userNo) {
        this.userNo = userNo;
    }
}